name: "Create Release"
description: "Send a notification to Slack"
inputs:
  change-log-file-full-path:
    description: "Path to the change log file"
    required: true
  version:
    description: "Version of the release"
    required: true
  github-token:
    description: "GitHub token for authentication"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get today's date
      id: get-today-date
      shell: bash
      run: echo "today=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ inputs.version }} # Tag for the release
        name: "Release ${{ inputs.version }}" # Custom release name
        body: "Release created on ${{ steps.get-today-date.outputs.today }}"
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ inputs.github-token }}
        file: ${{ inputs.change-log-file-full-path }}
        tag: ${{ inputs.version }}
